hyper:
  lr: 0.001
  epochs: 5
  batch_size: 15
  n_neurons: 64  
  with_skip_connections: True
  n_depth: 3
  patience: 5
data:
  train_size: 0.8
  in_memory: True
  static_test: True
  normalize: True
  p_flip_horizontal: 0.3
  sampling_height: 272
  sampling_width: 448
  random_train_test_split: True
  detector: "both"
compute:
  hpc: False
miscellaneous:
  save_as: "test_model.pth"
constants:
  seed: 42
  n_classes: 3
wandb:
  track: False
  project: "ionbeam"
  entity: "rasmustorp-ai"
bsub:
  queue: "gpua100"
  name: "ionbeam"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4

