hyper:
  lr: 0.001
  epochs: 100
  batch_size: 35
  n_neurons: 64  
  with_skip_connections: True
  n_depth: 3
  patience: 100
  hotstart_model: False
data:
  dataset: "11t51center"
  train_size: 0.2
  test_size: 0.2
  in_memory: True
  static_test: True
  random_train_test_split: True
  detector: "both"
dataAug:
  p_flip_horizontal: 0.0
  random_sampling_train: True
  sampling_height: 272
  sampling_width: 448
  normalize: True
  gaussian_kernel_size: 0
  gaussian_sigma: 0.
compute:
  hpc: False
miscellaneous:
  save_as: "NoModelName"
constants:
  seed: 42
  n_classes: 3
wandb:
  track: False
  project: "ionbeam"
  entity: "rasmustorp-ai"
bsub:
  queue: "gpua100"
  name: "ionbeam"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4

