hyper:
  lr: 0.001
  epochs: 100
  batch_size: 50
  n_neurons: 64  
  with_skip_connections: True
  n_depth: 3
  patience: 100
data:
  train_size: 0.2
  test_size: 0.2
  in_memory: True
  random_sampling_train: False
  static_test: True
  normalize: True
  p_flip_horizontal: 0.0
  sampling_height: 272
  sampling_width: 448
  random_train_test_split: True
  detector: "both"
compute:
  hpc: False
miscellaneous:
  save_as: "test_model.pth"
constants:
  seed: 42
  n_classes: 3
wandb:
  track: False
  project: "ionbeam"
  entity: "rasmustorp-ai"
bsub:
  queue: "gpua100"
  name: "ionbeam"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4

