hyper:
  lr: 0.001
  epochs: 15
  batch_size: 30
  n_neurons: 64
  square_size: 256
  in_memory: False
  static_test: True
  with_skip_connections: True
  n_depth: 3
  patience: 5
  train_size: 0.8
constants:
  seed: 42
  n_classes: 3
  n_channels: 2
  data_path: "data/"
wandb:
  track: False
  project: "ionbeam"
  entity: "rasmustorp-ai"
bsub:
  queue: "gpua100"
  name: "mnist"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4

